import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class ThemeProvider extends ChangeNotifier {
  bool _isDarkMode = false;
  String _currentLanguage = 'English'; // Default language

  bool get isDarkMode => _isDarkMode;
  String get currentLanguage => _currentLanguage;

  ThemeProvider() {
    _loadThemePreferences();
  }

  Future<void> _loadThemePreferences() async {
    final prefs = await SharedPreferences.getInstance();
    _isDarkMode = prefs.getBool('isDarkMode') ?? false;
    _currentLanguage = prefs.getString('selectedLanguage') ?? 'English';
    notifyListeners();
  }

  Future<void> toggleTheme() async {
    _isDarkMode = !_isDarkMode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('isDarkMode', _isDarkMode);
    notifyListeners();
  }

  Future<void> setLanguage(String language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('selectedLanguage', language);
    notifyListeners();
  }

  // Language translations
  Map<String, Map<String, String>> get translations => {
    'English': {
      'profile': 'Profile',
      'personal_information': 'Personal Information',
      'security_settings': 'Security Settings',
      'notification_preferences': 'Notification Preferences',
      'language': 'Language',
      'about': 'About',
      'help_support': 'Help & Support',
      'logout': 'Logout',
      'verified_user': 'Verified User',
      'documents': 'Documents',
      'applications': 'Applications',
      'completed': 'Completed',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'two_factor_auth': 'Two-Factor Authentication',
      'privacy_settings': 'Privacy Settings',
      'push_notifications': 'Push Notifications',
      'email_notifications': 'Email Notifications',
      'sms_notifications': 'SMS Notifications',
      'app_language': 'App Language',
      'version': 'Version',
      'terms_conditions': 'Terms & Conditions',
      'privacy_policy': 'Privacy Policy',
      'contact_support': 'Contact Support',
      'faq': 'FAQ',
      'logout_confirmation': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'yes_logout': 'Yes, Logout',
      'dashboard': 'Dashboard',
      'welcome_back': 'Welcome back',
      'manage_documents': 'Manage your government documents with ease',
      'document_expiry_overview': 'Document Expiry Overview',
      'expiring_soon': 'Expiring Soon',
      'active': 'Active',
      'expired': 'Expired',
      'quick_actions': 'Quick Actions',
      'renew_now': 'Renew Now',
      'apply_new': 'Apply New',
      'track_status': 'Track Status',
      'recent_applications': 'Recent Applications',
      'government_documents': 'Government Documents',
      'notifications': 'Notifications',
      'all': 'All',
      'expiry': 'Expiry',
      'status': 'Status',
      'updates': 'Updates',
      'security': 'Security',
      'mark_all_read': 'Mark All as Read',
      'clear_all': 'Clear All',
      'notification_settings': 'Notification Settings',
      'ai_chat': 'AI Chat',
      'online': 'Online',
      'type_message': 'Type your message...',
      'send': 'Send',
      'quick_actions_chat': 'Quick Actions',
      'renew_documents': 'Renew Documents',
      'check_status': 'Check Status',
      'form_help': 'Form Help',
      'expiry_dates': 'Expiry Dates',
      'clear_history': 'Clear History',
      'export_chat': 'Export Chat',
      'chat_settings': 'Chat Settings',
      'document_vault': 'Document Vault',
      'search_documents': 'Search documents...',
      'add_document': 'Add Document',
      'no_documents_found': 'No documents found',
      'try_adjusting_search': 'Try adjusting your search or filter criteria',
      'view_details': 'View Details',
      'download': 'Download',
      'share': 'Share',
      'official_website': 'Official Website',
      'document_information': 'Document Information',
      'category': 'Category',
      'document_number': 'Document Number',
      'issue_date': 'Issue Date',
      'expiry_date': 'Expiry Date',
      'last_updated': 'Last Updated',
      'file_size': 'File Size',
      'file_type': 'File Type',
      'secure_document': 'Secure Document',
      'encrypted_stored': 'This document is encrypted and stored securely. Only you can access it.',
      'edit_details': 'Edit Details',
      'delete_document': 'Delete Document',
      'view_history': 'View History',
      'delete_confirmation': 'Are you sure you want to delete this document?',
      'delete': 'Delete',
      'downloaded_successfully': 'downloaded successfully',
      'sharing': 'Sharing',
      'could_not_open_website': 'Could not open website',
      'official_website_not_available': 'Official website not available for this document.',
      'welcome': 'Welcome',
      'get_started': 'Get Started',
      'login': 'Login',
      'signup': 'Sign Up',
      'digilocker': 'DigiLocker',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'continue_with_digilocker': 'Continue with DigiLocker',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'confirm_password': 'Confirm Password',
      'agree_terms': 'I agree to the Terms & Conditions',
      'create_account': 'Create Account',
      'connect_digilocker': 'Connect DigiLocker',
      'benefits': 'Benefits',
      'secure_access': 'Secure access to all your government documents',
      'auto_form_filling': 'Auto form filling for applications',
      'expiry_reminders': 'Expiry reminders and notifications',
      'permissions_required': 'Permissions Required',
      'read_documents': 'Read your documents',
      'update_information': 'Update your information',
      'send_notifications': 'Send notifications',
      'connect_now': 'Connect Now',
      'kyc_completion': 'KYC Completion',
      'verify_information': 'Please verify your information',
      'name': 'Name',
      'date_of_birth': 'Date of Birth',
      'address': 'Address',
      'confirm_continue': 'Confirm & Continue',
      'start_conversation': 'Start a conversation',
      'ask_about_documents': 'Ask me anything about your government documents',
      'aadhaar_card': 'Aadhaar Card',
      'pan_card': 'PAN Card',
      'driving_license': 'Driving License',
      'passport': 'Passport',
      'voter_id': 'Voter ID',
      'birth_certificate': 'Birth Certificate',
      'in_progress': 'In Progress',
      'pending': 'Pending',
      'completed_status': 'Completed',
      'home': 'Home',
      'document_manager': 'Document Manager',
      'loading_documents': 'Loading your secure documents...',
      'secure_document_storage': 'Secure Document Storage',
      'auto_form_filling': 'Auto Form Filling',
      'expiry_reminders': 'Expiry Reminders',
      'real_time_tracking': 'Real-time Tracking',
      'encrypted_vault': 'Encrypted Vault',
      'multilingual_support': 'Multilingual Support',
      'ai_chatbot_helpdesk': 'AI Chatbot Helpdesk',
      'payments_integration': 'Payments Integration',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'or': 'or',
      'continue_with_google': 'Continue with Google',
      'continue_with_facebook': 'Continue with Facebook',
      'by_continuing': 'By continuing, you agree to our',
      'terms_of_service': 'Terms of Service',
      'and': 'and',
      'privacy_policy_link': 'Privacy Policy',
      'phone_number_label': 'Phone Number',
      'otp': 'OTP',
      'resend_otp': 'Resend OTP',
      'verify_otp': 'Verify OTP',
      'didnt_receive': "Didn't receive the code?",
      'enter_otp': 'Enter the OTP sent to',
      'otp_sent': 'OTP sent to',
      'verify': 'Verify',
      'back_to_login': 'Back to Login',
      'enter_phone': 'Enter your phone number',
      'phone_hint': 'Enter 10-digit mobile number',
      'send_otp': 'Send OTP',
      'enter_otp_hint': 'Enter 6-digit OTP',
      'verify_and_continue': 'Verify & Continue',
      'otp_verification': 'OTP Verification',
      'phone_verification': 'Phone Verification',
      'welcome_to_aaram': 'Welcome to AARAM',
      'your_personal_ai': 'Your Personal AI Assistant for Government Documents',
      'features_intro': 'Manage, track, and renew all your government documents with AI-powered assistance',
      'get_started_button': 'Get Started',
      'already_have_account_text': 'Already have an account?',
      'sign_in_link': 'Sign In',
      'create_new_account': 'Create New Account',
      'join_aaram': 'Join AARAM today and experience hassle-free document management',
      'full_name_hint': 'Enter your full name',
      'email_hint': 'Enter your email address',
      'phone_hint_signup': 'Enter your phone number',
      'password_hint': 'Create a strong password',
      'confirm_password_hint': 'Confirm your password',
      'agree_to_terms': 'I agree to the Terms & Conditions',
      'create_account_button': 'Create Account',
      'or_signup_with': 'or sign up with',
      'have_account_text': 'Have an account?',
      'sign_in_button': 'Sign In',
      'welcome_back_text': 'Welcome back!',
      'sign_in_to_continue': 'Sign in to continue managing your documents',
      'email_or_phone': 'Email or Phone',
      'password_label': 'Password',
      'forgot_password_link': 'Forgot Password?',
      'sign_in_with_password': 'Sign In with Password',
      'or_signin_with': 'or sign in with',
      'dont_have_account_text': "Don't have an account?",
      'sign_up_link': 'Sign Up',
      'connect_digilocker_title': 'Connect DigiLocker',
      'secure_access_description': 'Get secure access to all your government documents',
      'auto_form_filling_desc': 'Automatically fill forms using your verified documents',
      'expiry_reminders_desc': 'Never miss document expiry dates with smart reminders',
      'permissions_needed': 'Permissions Needed',
      'read_documents_desc': 'Read your documents from DigiLocker',
      'update_info_desc': 'Update your information when needed',
      'send_notifications_desc': 'Send you important notifications',
      'connect_digilocker_button': 'Connect DigiLocker',
      'learn_more': 'Learn More',
      'official_website': 'Official Website',
      'kyc_completion_title': 'KYC Completion',
      'verify_your_info': 'Please verify your information',
      'name_label': 'Name',
      'date_of_birth_label': 'Date of Birth',
      'address_label': 'Address',
      'confirm_and_continue_button': 'Confirm & Continue',
      'edit_info': 'Edit Info',
      'notifications_title': 'Notifications',
      'filter_notifications': 'Filter notifications',
      'mark_all_read_button': 'Mark All as Read',
      'clear_all_button': 'Clear All',
      'notification_settings_button': 'Notification Settings',
      'no_notifications': 'No notifications yet',
      'no_notifications_desc': 'You\'re all caught up! New notifications will appear here.',
      'notification_item_title': 'Document Expiry Reminder',
      'notification_item_desc': 'Your Aadhaar card will expire in 30 days',
      'notification_time': '2 hours ago',
      'notification_item_title2': 'Application Status Update',
      'notification_item_desc2': 'Your PAN card application has been approved',
      'notification_time2': '1 day ago',
      'notification_item_title3': 'Security Alert',
      'notification_item_desc3': 'New login detected from a new device',
      'notification_time3': '3 days ago',
    },
    'Malayalam': {
      'profile': 'പ്രൊഫൈൽ',
      'personal_information': 'വ്യക്തിഗത വിവരങ്ങൾ',
      'security_settings': 'സുരക്ഷാ ക്രമീകരണങ്ങൾ',
      'notification_preferences': 'അറിയിപ്പ് മുൻഗണനകൾ',
      'language': 'ഭാഷ',
      'about': 'കുറിച്ച്',
      'help_support': 'സഹായം & പിന്തുണ',
      'logout': 'ലോഗൗട്ട്',
      'verified_user': 'സാധൂകരിച്ച ഉപയോക്താവ്',
      'documents': 'ഡോക്യുമെന്റുകൾ',
      'applications': 'അപേക്ഷകൾ',
      'completed': 'പൂർത്തിയായി',
      'edit_profile': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'change_password': 'പാസ്വേഡ് മാറ്റുക',
      'two_factor_auth': 'രണ്ട് ഘടക ഓഥന്റിക്കേഷൻ',
      'privacy_settings': 'സ്വകാര്യത ക്രമീകരണങ്ങൾ',
      'push_notifications': 'പുഷ് അറിയിപ്പുകൾ',
      'email_notifications': 'ഇമെയിൽ അറിയിപ്പുകൾ',
      'sms_notifications': 'എസ്എംഎസ് അറിയിപ്പുകൾ',
      'app_language': 'ആപ്പ് ഭാഷ',
      'version': 'പതിപ്പ്',
      'terms_conditions': 'നിബന്ധനകൾ & വ്യവസ്ഥകൾ',
      'privacy_policy': 'സ്വകാര്യത നയം',
      'contact_support': 'പിന്തുണയുമായി ബന്ധപ്പെടുക',
      'faq': 'പതിവ് ചോദ്യങ്ങൾ',
      'logout_confirmation': 'ലോഗൗട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?',
      'cancel': 'റദ്ദാക്കുക',
      'yes_logout': 'അതെ, ലോഗൗട്ട്',
      'dashboard': 'ഡാഷ്ബോർഡ്',
      'welcome_back': 'വീണ്ടും സ്വാഗതം',
      'manage_documents': 'നിങ്ങളുടെ സർക്കാർ ഡോക്യുമെന്റുകൾ എളുപ്പത്തിൽ നിയന്ത്രിക്കുക',
      'document_expiry_overview': 'ഡോക്യുമെന്റ് കാലഹരണപ്പെടൽ അവലോകനം',
      'expiring_soon': 'ഉടൻ കാലഹരണപ്പെടും',
      'active': 'സജീവം',
      'expired': 'കാലഹരണപ്പെട്ടു',
      'quick_actions': 'വേഗ പ്രവർത്തനങ്ങൾ',
      'renew_now': 'ഇപ്പോൾ പുനർനവീകരിക്കുക',
      'apply_new': 'പുതിയത് അപേക്ഷിക്കുക',
      'track_status': 'നില പിന്തുടരുക',
      'recent_applications': 'സമീപകാല അപേക്ഷകൾ',
      'government_documents': 'സർക്കാർ ഡോക്യുമെന്റുകൾ',
      'notifications': 'അറിയിപ്പുകൾ',
      'all': 'എല്ലാം',
      'expiry': 'കാലഹരണപ്പെടൽ',
      'status': 'നില',
      'updates': 'പുതുക്കലുകൾ',
      'security': 'സുരക്ഷ',
      'mark_all_read': 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
      'clear_all': 'എല്ലാം മായ്ക്കുക',
      'notification_settings': 'അറിയിപ്പ് ക്രമീകരണങ്ങൾ',
      'ai_chat': 'എഐ ചാറ്റ്',
      'online': 'ഓൺലൈൻ',
      'type_message': 'നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      'send': 'അയയ്ക്കുക',
      'quick_actions_chat': 'വേഗ പ്രവർത്തനങ്ങൾ',
      'renew_documents': 'ഡോക്യുമെന്റുകൾ പുനർനവീകരിക്കുക',
      'check_status': 'നില പരിശോധിക്കുക',
      'form_help': 'ഫോം സഹായം',
      'expiry_dates': 'കാലഹരണപ്പെടൽ തീയതികൾ',
      'clear_history': 'ചരിത്രം മായ്ക്കുക',
      'export_chat': 'ചാറ്റ് എക്സ്പോർട്ട് ചെയ്യുക',
      'chat_settings': 'ചാറ്റ് ക്രമീകരണങ്ങൾ',
      'document_vault': 'ഡോക്യുമെന്റ് വോൾട്ട്',
      'search_documents': 'ഡോക്യുമെന്റുകൾ തിരയുക...',
      'add_document': 'ഡോക്യുമെന്റ് ചേർക്കുക',
      'no_documents_found': 'ഡോക്യുമെന്റുകൾ കണ്ടെത്തിയില്ല',
      'try_adjusting_search': 'നിങ്ങളുടെ തിരയൽ അല്ലെങ്കിൽ ഫിൽട്ടർ മാനദണ്ഡങ്ങൾ ക്രമീകരിക്കാൻ ശ്രമിക്കുക',
      'view_details': 'വിവരങ്ങൾ കാണുക',
      'download': 'ഡൗൺലോഡ്',
      'share': 'പങ്കുവെയ്ക്കുക',
      'official_website': 'ഔദ്യോഗിക വെബ്സൈറ്റ്',
      'document_information': 'ഡോക്യുമെന്റ് വിവരങ്ങൾ',
      'category': 'വിഭാഗം',
      'document_number': 'ഡോക്യുമെന്റ് നമ്പർ',
      'issue_date': 'ഇഷ്യൂ തീയതി',
      'expiry_date': 'കാലഹരണപ്പെടൽ തീയതി',
      'last_updated': 'അവസാനം അപ്ഡേറ്റ് ചെയ്തത്',
      'file_size': 'ഫയൽ വലുപ്പം',
      'file_type': 'ഫയൽ തരം',
      'secure_document': 'സുരക്ഷിത ഡോക്യുമെന്റ്',
      'encrypted_stored': 'ഈ ഡോക്യുമെന്റ് എൻക്രിപ്റ്റ് ചെയ്ത് സുരക്ഷിതമായി സൂക്ഷിച്ചിരിക്കുന്നു. നിങ്ങൾക്ക് മാത്രമേ ഇത് ആക്സസ് ചെയ്യാൻ കഴിയൂ.',
      'edit_details': 'വിവരങ്ങൾ എഡിറ്റ് ചെയ്യുക',
      'delete_document': 'ഡോക്യുമെന്റ് ഇല്ലാതാക്കുക',
      'view_history': 'ചരിത്രം കാണുക',
      'delete_confirmation': 'ഈ ഡോക്യുമെന്റ് ഇല്ലാതാക്കണമെന്ന് ഉറപ്പാണോ?',
      'delete': 'ഇല്ലാതാക്കുക',
      'downloaded_successfully': 'വിജയകരമായി ഡൗൺലോഡ് ചെയ്തു',
      'sharing': 'പങ്കുവെയ്ക്കുന്നു',
      'could_not_open_website': 'വെബ്സൈറ്റ് തുറക്കാൻ കഴിഞ്ഞില്ല',
      'official_website_not_available': 'ഈ ഡോക്യുമെന്റിന് ഔദ്യോഗിക വെബ്സൈറ്റ് ലഭ്യമല്ല.',
      'welcome': 'സ്വാഗതം',
      'get_started': 'ആരംഭിക്കുക',
      'login': 'ലോഗിൻ',
      'signup': 'സൈൻ അപ്പ്',
      'digilocker': 'ഡിജിലോക്കർ',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്വേഡ്',
      'forgot_password': 'പാസ്വേഡ് മറന്നോ?',
      'continue_with_digilocker': 'ഡിജിലോക്കർ ഉപയോഗിച്ച് തുടരുക',
      'dont_have_account': 'അക്കൗണ്ട് ഇല്ലേ?',
      'already_have_account': 'അക്കൗണ്ട് ഇതിനകം ഉണ്ടോ?',
      'full_name': 'പൂർണ്ണ നാമം',
      'phone_number': 'ഫോൺ നമ്പർ',
      'confirm_password': 'പാസ്വേഡ് സ്ഥിരീകരിക്കുക',
      'agree_terms': 'നിബന്ധനകൾ & വ്യവസ്ഥകൾ സമ്മതിക്കുന്നു',
      'create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'connect_digilocker': 'ഡിജിലോക്കർ ബന്ധിപ്പിക്കുക',
      'benefits': 'ആനുകൂല്യങ്ങൾ',
      'secure_access': 'നിങ്ങളുടെ എല്ലാ സർക്കാർ ഡോക്യുമെന്റുകൾക്കും സുരക്ഷിത ആക്സസ്',
      'auto_form_filling': 'അപേക്ഷകൾക്കുള്ള ഓട്ടോ ഫോം പൂരിപ്പിക്കൽ',
      'expiry_reminders': 'കാലഹരണപ്പെടൽ ഓർമ്മപ്പെടുത്തലുകളും അറിയിപ്പുകളും',
      'permissions_required': 'ആവശ്യമായ അനുമതികൾ',
      'read_documents': 'നിങ്ങളുടെ ഡോക്യുമെന്റുകൾ വായിക്കുക',
      'update_information': 'നിങ്ങളുടെ വിവരങ്ങൾ അപ്ഡേറ്റ് ചെയ്യുക',
      'send_notifications': 'അറിയിപ്പുകൾ അയയ്ക്കുക',
      'connect_now': 'ഇപ്പോൾ ബന്ധിപ്പിക്കുക',
      'kyc_completion': 'കെവൈസി പൂർത്തീകരണം',
      'verify_information': 'ദയവായി നിങ്ങളുടെ വിവരങ്ങൾ സാധൂകരിക്കുക',
      'name': 'പേര്',
      'date_of_birth': 'ജനന തീയതി',
      'address': 'വിലാസം',
      'confirm_continue': 'സ്ഥിരീകരിച്ച് തുടരുക',
      'start_conversation': 'ഒരു സംഭാഷണം ആരംഭിക്കുക',
      'ask_about_documents': 'നിങ്ങളുടെ സർക്കാർ ഡോക്യുമെന്റുകളെക്കുറിച്ച് എന്തും ചോദിക്കാം',
      'aadhaar_card': 'ആധാർ കാർഡ്',
      'pan_card': 'പാൻ കാർഡ്',
      'driving_license': 'ഡ്രൈവിംഗ് ലൈസൻസ്',
      'passport': 'പാസ്പോർട്ട്',
      'voter_id': 'വോട്ടർ ഐഡി',
      'birth_certificate': 'ജനന സർട്ടിഫിക്കറ്റ്',
      'in_progress': 'പുരോഗതിയിൽ',
      'pending': 'തീരുമാനിക്കാത്തത്',
      'completed_status': 'പൂർത്തിയായി',
      'home': 'അനുഭവം',
      'document_manager': 'Document Manager',
      'loading_documents': 'Loading your secure documents...',
      'secure_document_storage': 'Secure Document Storage',
      'auto_form_filling': 'Auto Form Filling',
      'expiry_reminders': 'Expiry Reminders',
      'real_time_tracking': 'Real-time Tracking',
      'encrypted_vault': 'Encrypted Vault',
      'multilingual_support': 'Multilingual Support',
      'ai_chatbot_helpdesk': 'AI Chatbot Helpdesk',
      'payments_integration': 'Payments Integration',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'or': 'or',
      'continue_with_google': 'Continue with Google',
      'continue_with_facebook': 'Continue with Facebook',
      'by_continuing': 'By continuing, you agree to our',
      'terms_of_service': 'Terms of Service',
      'and': 'and',
      'privacy_policy_link': 'Privacy Policy',
      'phone_number_label': 'Phone Number',
      'otp': 'OTP',
      'resend_otp': 'Resend OTP',
      'verify_otp': 'Verify OTP',
      'didnt_receive': "Didn't receive the code?",
      'enter_otp': 'Enter the OTP sent to',
      'otp_sent': 'OTP sent to',
      'verify': 'Verify',
      'back_to_login': 'Back to Login',
      'enter_phone': 'Enter your phone number',
      'phone_hint': 'Enter 10-digit mobile number',
      'send_otp': 'Send OTP',
      'enter_otp_hint': 'Enter 6-digit OTP',
      'verify_and_continue': 'Verify & Continue',
      'otp_verification': 'OTP Verification',
      'phone_verification': 'Phone Verification',
      'welcome_to_aaram': 'Welcome to AARAM',
      'your_personal_ai': 'Your Personal AI Assistant for Government Documents',
      'features_intro': 'Manage, track, and renew all your government documents with AI-powered assistance',
      'get_started_button': 'Get Started',
      'already_have_account_text': 'Already have an account?',
      'sign_in_link': 'Sign In',
      'create_new_account': 'Create New Account',
      'join_aaram': 'Join AARAM today and experience hassle-free document management',
      'full_name_hint': 'Enter your full name',
      'email_hint': 'Enter your email address',
      'phone_hint_signup': 'Enter your phone number',
      'password_hint': 'Create a strong password',
      'confirm_password_hint': 'Confirm your password',
      'agree_to_terms': 'I agree to the Terms & Conditions',
      'create_account_button': 'Create Account',
      'or_signup_with': 'or sign up with',
      'have_account_text': 'Have an account?',
      'sign_in_button': 'Sign In',
      'welcome_back_text': 'Welcome back!',
      'sign_in_to_continue': 'Sign in to continue managing your documents',
      'email_or_phone': 'Email or Phone',
      'password_label': 'Password',
      'forgot_password_link': 'Forgot Password?',
      'sign_in_with_password': 'Sign In with Password',
      'or_signin_with': 'or sign in with',
      'dont_have_account_text': "Don't have an account?",
      'sign_up_link': 'Sign Up',
      'connect_digilocker_title': 'Connect DigiLocker',
      'secure_access_description': 'Get secure access to all your government documents',
      'auto_form_filling_desc': 'Automatically fill forms using your verified documents',
      'expiry_reminders_desc': 'Never miss document expiry dates with smart reminders',
      'permissions_needed': 'Permissions Needed',
      'read_documents_desc': 'Read your documents from DigiLocker',
      'update_info_desc': 'Update your information when needed',
      'send_notifications_desc': 'Send you important notifications',
      'connect_digilocker_button': 'Connect DigiLocker',
      'learn_more': 'Learn More',
      'official_website': 'Official Website',
      'kyc_completion_title': 'KYC Completion',
      'verify_your_info': 'Please verify your information',
      'name_label': 'Name',
      'date_of_birth_label': 'Date of Birth',
      'address_label': 'Address',
      'confirm_and_continue_button': 'Confirm & Continue',
      'edit_info': 'Edit Info',
      'notifications_title': 'Notifications',
      'filter_notifications': 'Filter notifications',
      'mark_all_read_button': 'Mark All as Read',
      'clear_all_button': 'Clear All',
      'notification_settings_button': 'Notification Settings',
      'no_notifications': 'No notifications yet',
      'no_notifications_desc': 'You\'re all caught up! New notifications will appear here.',
      'notification_item_title': 'Document Expiry Reminder',
      'notification_item_desc': 'Your Aadhaar card will expire in 30 days',
      'notification_time': '2 hours ago',
      'notification_item_title2': 'Application Status Update',
      'notification_item_desc2': 'Your PAN card application has been approved',
      'notification_time2': '1 day ago',
      'notification_item_title3': 'Security Alert',
      'notification_item_desc3': 'New login detected from a new device',
      'notification_time3': '3 days ago',
    },
  };

  String getText(String key) {
    return translations[_currentLanguage]?[key] ?? key;
  }
} 